dist: trusty
language: rust
cache: cargo

rust:
  - nightly
  - beta
# Rust Edition 2018 is not yet stable.
#  - stable

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email: false
