language: rust
dist: xenial
osx_image: xcode10.1
cache: cargo

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  homebrew:
    packages:
      - node
      - yarn
      - python3

before_install:
  - cargo --version
  - node --version
  - bash --version
  - python --version
  - python3 --version

install:
  - pip3 install -r tools/requirements.txt

script:
  - "cd src/config/ui && yarn && yarn build && cd ../../.."
  - cargo build --release
  - cargo run --release -- --doctor
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench; fi
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test; fi
  - ./tools/run-blackbox-tests.py --release

notifications:
  email: false
