language: rust
dist: xenial
osx_image: xcode10.1
cache: cargo

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: beta
    - rust: stable

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  homebrew:
    packages:
      - node
      - yarn
      - python3

before_install:
  - cargo --version
  - bash --version
  - python --version
  - python3 --version

install:
  - pip3 install -r tools/requirements.txt

script:
  - "cd src/config/ui && yarn && yarn build && cd ../../.."
  - cargo test
  - cargo build --release
  - cargo run -- --doctor
  - cargo bench
  - ./tools/run-blackbox-tests.py

notifications:
  email: false
