dist: xenial
language: rust
cache: cargo

rust:
  - nightly
  - beta
# Rust Edition 2018 is not yet stable.
#  - stable

before_install:
  - cargo --version
  - bash --version
  - python --version
  - python3 --version

script:
  - cargo build
  - cargo build --release
  - cargo test
  - ./tools/run-blackbox-tests.py

notifications:
  email: false
