dist: xenial
language: rust
cache: cargo

rust:
  - nightly
  - beta
# Rust Edition 2018 is not yet stable.
#  - stable

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

before_install:
  - cargo --version
  - bash --version
  - python --version
  - python3 --version

install:
  - pip3 install -r tools/requirements.txt

script:
  - "cd src/config/ui; yarn; yarn build; cd ../../.."
  - cargo test
  - cargo build --release
  - ./tools/run-blackbox-tests.py

notifications:
  email: false
