language: rust
dist: xenial
osx_image: xcode10.1
cache: cargo

os:
  - linux
  - osx

rust:
  - nightly
  - beta
  - stable

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
  homebrew:
    update: true
    packages:
      - python

before_install:
  - cargo --version
  - bash --version
  - python --version

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link --overwrite python; fi
  - pip3 install -r tools/requirements.txt

script:
  - cargo build --release
  - cargo run --release -- --doctor
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo bench; fi
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --release; fi
  - ./run-tests.py --release

notifications:
  email: false
