[package]
name = "nsh"
version = "0.1.0"
authors = ["Seiya Nuta <nuta@seiya.me>"]

[dependencies]
lazy_static = "*"
log = "*"
slog = "*"
slog-scope = "*"
slog-stdlog = "*"
slog-term = "*"
nom = "4"
rustyline = "2"
nix = "0.11"
clap = "2"
dirs = "1"